name: Build android apk

on:
  push:
    branches: [ "master" ]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: mv build/app/outputs/flutter-apk/app-release.apk ./${{ github.ref_name }}.apk

      - name: apk Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/${{github.ref_name}}-windows.zip